events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile on;

    gzip on;
    gzip_types text/plain text/css application/json text/xml application/xml text/javascript;
    gzip_min_length 1024;

    log_format json_combined escape=json
      '{'
        '"time":"$time_iso8601",'
        '"service":"front-nginx",'
        '"request_id":"$request_id",'
        '"remote_addr":"$remote_addr",'
        '"method":"$request_method",'
        '"uri":"$request_uri",'
        '"status":"$status",'
        '"body_bytes_sent":"$body_bytes_sent",'
        '"request_time":"$request_time",'
        '"upstream_response_time":"$upstream_response_time",'
        '"http_referer":"$http_referer",'
        '"http_user_agent":"$http_user_agent"'
      '}';
    access_log /dev/stdout json_combined;
    error_log  /dev/stderr warn;

    include /etc/nginx/conf.d/*.conf;
}
